name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: Multiline Command
        run: |
          node -v
          npm -v
  # Job Paralelo
  parallel-jobs-macos:
    runs-on: macos-latest
    steps:
      - name: View  SW Version
        run: sw_vers
  # Job dependente
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windowoos String"
      - name: Error Step
        run: doesnotexist

